Adyen/adyen-magento2-express-checkout

Model/ExpressInit.php

Fix the usage of the `collectTotals()` method for the quote created in product detail page. Missing quote totals causes `amount/value` not being added to the `/paymentMethods` call request and Apple Pay tx_variant doesn't return in the payment methods in this case.
- Apple Pay express from product detail page and minicart.

[PW-7999] Fix quote totals for PDP express initialisation

---

view/frontend/web/js/applepay/button.js
view/frontend/web/js/googlepay/button.js

Instead of building the `stateData` manually on the frontend, web component's state data added to the `payment-information` payload.
- GooglePay
Fixes #22

[PW-8234] Add missing browserInfo to the payment request

---

view/frontend/web/js/googlepay/button.js

Due to the separate JS files we need to update the adyen_hpp to adyen_googlepay for these payment methods for RC-V9. 
Tested express checkout including tokenization. 

[PW-8356] - Add RC-V9 Support GooglePay

---

composer.json
view/frontend/web/js/applepay/button.js

After migrating to separate payment methods, version 9 of the payment plugin doesn't have `adyen_hpp` payment method. Correct payment method code of Apple Pay request was updated with this PR.
- Apple Pay exress payment

[PW-8640] Modify payment method code of Apple Pay request

---

Model/ConfigurationInterface.php
README.md
Setup/Patch/Data/UpdateExpressDBPaths.php
etc/adminhtml/system.xml
etc/adminhtml/system/adyen_online_checkout.xml

After changing the configuration page design on V9, the Express Modules' configuration fields are revisited with this PR
- setup Express methods in the admin panel and test the payments

[ECP-8666] Revisit Express Checkout configuration fields

---

view/frontend/web/js/applepay/button.js
view/frontend/web/js/googlepay/button.js

Fix the Taxation in order to have it working for 2.4.6^ As the tax shouldn't be done by us but by the Magento Platform in a correct fashion. 
Googlepay Tax Correct in multiple regions

[ECP-8701] - Fix the Taxation for 2.4.6

---

view/frontend/templates/applepay/shortcut.phtml
view/frontend/web/js/applepay/button.js

Hide Apple Pay component by default and display it only if method is available. Avoids front-side edge effects if the component is not displayed.
I also add an `onNotAvailable` function to avoid having to copy the whole function in case of modification in a theme.
**Fixed issue**:  #54

Hide Apple Pay component by default and display it only if method is available

---

view/frontend/web/js/applepay/button.js

This PR changes the merchant name displayed in Apple Pay. By default it is the name of the merchant Adyen that is displayed, the user can easily change this value via a mixin.
**Fixed issue**:  #57

Apple Pay - Display merchant name in Label

---

Block/ApplePay/Shortcut/Button.php
Model/Config/Source/ApplePay/ButtonColor.php
Model/Config/Source/ShortcutAreas.php
Model/Configuration.php
Model/ConfigurationInterface.php
etc/adminhtml/system/adyen_hpp.xml
view/frontend/templates/applepay/shortcut.phtml
view/frontend/web/js/applepay/button.js
view/frontend/web/js/helpers/getApplePayStyles.js

This PR adds the ability to choose the style of the Apple Pay button. In addition, the GooglePay and Apple Pay methods are separated into 2 different groups to improve configuration management.
Issue: #50

Add Apple Pay button color option

---

view/frontend/web/js/applepay/button.js

Replace fake billing phone (ie: `0000000000`) by contact phone for Apple Pay express checkout.
**Fixed issue**:  #61

Apple Pay - Replace fake billing phone by contact phone

---

.github/workflows/e2e.yml
.github/workflows/main.yml
Model/ConfigurationInterface.php
README.md
Setup/Patch/Data/UpdateExpressDBPaths.php
composer.json
etc/adminhtml/system.xml
etc/adminhtml/system/adyen_online_checkout.xml
etc/module.xml
view/frontend/web/js/applepay/button.js
view/frontend/web/js/googlepay/button.js

Merge rc-v2 into develop

---

view/frontend/web/js/googlepay/button.js

Adobe Commerce provides the opportunity to show the shopping method even though it's not available for the given card. This behaviour can be applied by setting the value of `Configuration / Sales / Shipping Method / Free Shipping / 
Show Method if Not Applicable` config field to `Yes`.
Even though the shipping method is transferred to the frontend, `method_code` of this shipping method will be empty. This triggers the issue of undefined method_code.
This PR solves this issue by unsetting the shipping method if it's not available just by checking the value of `available` property.
- Two shipping methods of which one of them is unavailable but set to be shown on the checkout.

[ECP-8770-v2] Fix shipping method parsing error

---

view/frontend/web/js/googlepay/button.js

Adobe Commerce provides the opportunity to show the shopping method even though it's not available for the given card. This behaviour can be applied by setting the value of `Configuration / Sales / Shipping Method / Free Shipping / 
Show Method if Not Applicable` config field to `Yes`.
Even though the shipping method is transferred to the frontend, `method_code` of this shipping method will be empty. This triggers the issue of undefined method_code.
This PR solves this issue by unsetting the shipping method if it's not available just by checking the value of `available` property.
- Two shipping methods of which one of them is unavailable but set to be shown on the checkout.

[ECP-8770-v1] Fix shipping method parsing error

---

view/frontend/web/js/googlepay/button.js

After the changes on V9 of main payment module, it was seen that Google Pay express couldn't redirect shopper to success page. The issue was main module couldn't fetch the `quoteId` from `quote` object on product detail page. Because, `quote` object is not available at that moment.
This PR applies the fix [2462](https://github.com/Adyen/adyen-magento2/pull/2462) to express module repository.
- Tested Googlepay payment on product, cart and minicart view.

[ECP-8907] - Fix Google Pay redirect to success page after payment

---

Model/GetAdyenPaymentMethodsByProduct.php

Fix 500 Error on /rest/V1/adyen/express/init/mine
```
Error: Call to undefined method Adyen\Payment\Helper\Data::getAdyenAbstractConfigData() in /var/www/html/vendor/adyen/adyen-magento2-expresscheckout/Model/GetAdyenPaymentMethodsByProduct.php:81
Stack trace:
#0 /var/www/html/vendor/adyen/adyen-magento2-expresscheckout/Model/ExpressDataBuilder.php(235): Adyen\ExpressCheckout\Model\GetAdyenPaymentMethodsByProduct->execute()
#1 /var/www/html/vendor/adyen/adyen-magento2-expresscheckout/Model/ExpressDataBuilder.php(172): Adyen\ExpressCheckout\Model\ExpressDataBuilder->getAdyenPaymentMethods()
#2 /var/www/html/vendor/adyen/adyen-magento2-expresscheckout/Model/ExpressInit.php(200): Adyen\ExpressCheckout\Model\ExpressDataBuilder->execute()
#3 [internal function]: …
```

[ECP-8905] Call config data from config helper instead 

---

view/frontend/web/js/applepay/button.js

Add `onAvailable` event for Apple Pay component. 
Resolves #81 81

Add onAvailable event for Apple Pay

---

view/frontend/web/js/actions/getExpressMethods.js
view/frontend/web/js/applepay/button.js
view/frontend/web/js/googlepay/button.js
view/frontend/web/js/helpers/manageQuoteIdOnPageRefresh.js

On product page for express checkouts, the quote-id is being created every time the page is refreshed on the browser and as a result a multiple entries exist in the `quote` table for the same product. This happens for both logged in or guest user where quote id is maintained for the session but not through refresh. This PR includes storing the quote-id to JS local storage variable and accessing it whenever `getRequest` method is called, to check whether there is an existing quote-id, if not then  let `getRequest` create a new one.
1. Quote-id is retained on page refresh
2. On visiting a different product page than the current one, the previous quote-id is removed 

[ECP-9230] Prevent refreshing Quote ID during page refresh on product page for express payment

---

view/frontend/web/js/googlepay/button.js

Using the new adyen-payment-service.js for GooglePayExpress Payments to handle /payment-details calls.

GooglePay Express payment for loggedIn user fails

---

etc/payment.xml

A new payment method group `adyen-express-payment-method` was introduced for `adyen_paypal_express` payment method, but this group wasn't defined in the `payment.xml` and therefore it was failing to retrieve the label information when it was trying to access `$this->_getOptions()->label` failing in successful displaying the order details page.

Solving the issue of broken Order view page after installing express checkout

---

.github/workflows/main.yml
Model/Resolver/ExpressInitResolver.php
Test/Unit/Model/Resolver/ExpressInitResolverTest.php
Test/bootstrap.php
Test/phpunit.xml
composer.json
etc/schema.graphqls

This PR introduces a new GraphQL mutation to initiate express payment quote on product detail page (PDP). Please see the schema definition for the usage. Adyen docs link will be added soon to this PR.
Besides the mutation implementation unit and API functional test suites have been created.
- Unit tests
- GraphQL API functional tests

[ECP-9440] Implement GraphQL mutation to initiate express quote on PDP

---

Model/Resolver/ExpressCancelResolver.php
Test/Unit/Model/Resolver/ExpressCancelResolverTest.php
Test/api-functional/GraphQl/AdyenExpressTest.php
etc/schema.graphqls

This PR implements `expressCancel` GraphQL mutation to cancel the express quote generated on product detail page (PDP). Unit and API functional tests were also provided.
- Unit tests
- API functional tests

[ECP-9442] Implement expressCancel mutation to cancel express quote on PDP

---

.github/Dockerfile
.github/Makefile
.github/config/php.ini
.github/docker-compose.yml
.github/scripts/install_magento.sh
.github/workflows/graphql-test.yml
.github/workflows/main.yml
Model/Resolver/ExpressActivateResolver.php
Model/Resolver/ExpressCancelResolver.php
Model/Resolver/ExpressInitResolver.php
Test/Unit/Model/Resolver/ExpressActivateResolverTest.php
Test/Unit/Model/Resolver/ExpressCancelResolverTest.php
Test/Unit/Model/Resolver/ExpressInitResolverTest.php
Test/api-functional/GraphQl/AdyenExpressTest.php
Test/bootstrap.php
Test/phpunit.xml
Test/phpunit_graphql.php
composer.json
etc/schema.graphqls
sonar-project.properties

This PR introduces GraphQL mutations to support headless express integration using GraphQL. As a part of the implementation following mutations were created.
- `expressInit`
- `expressActivate`
- `expressCancel`
Beside implementing those mutations, PHPUnit unit testing and API functional testing frameworks have been implemented.
- Unit tests
- API functional tests

Implement GraphQL mutations to support headless express payments on PDP

---

view/frontend/web/js/applepay/button.js

Currently when using Apple Pay Express if there are multiple shipping methods available all but the first are ignored and you cannot change your shipping method.
Changed the `onShippingContactSelect` to pass the full array of returned shipping methods into the `afterSetTotalsInfo`. This function then checks if the parameter is an array and if it is will set the `newShippingMethods` so that all shipping methods can be used.
The `onShippingMethodSelect` hasn't been changed and that still passes the single shipping method into the `afterSetTotalsInfo` function as we don't need to change the shipping methods on this callback.
Tested with Apple Pay using a sandbox Adyen account for delivery addresses with multiple, a single and no shipping methods available.
Adobe Commerce Version: 2.4.5-p9 …

Add shipping methods into Apple Pay Express

---

.github/workflows/create-release.yml

**Description**
Since `GITHUB_TOKEN` does not trigger workflows, we don't have visibility on release pull requests. With this PR, we have introduced the usage of PAT to trigger workflows.

[ECP-9535] Start using PAT instead of Github token for release automation

---

.github/workflows/e2e.yml

**Description**
Github deprecated artifacts action version 3 and this causes immediate cancellation on E2E test workflow. This PR bumps the action version to v4 to tackle this issue. 
**Tested scenarios**
- Successful build of E2E workflow

[ECP-9598] Bump Github Actions Artifacts version to V4 on E2E workflow

---

etc/config.xml

With the implementation of PayPal Express, when the Express module is enabled there are two PayPal tokenization options available in the admin tokenization settings in Magento.
When express is disabled, there is only one. Ideally they should both fall under one and seems to be because PayPal Express is implemented as a separate payment method.
This PR aims at having single Paypal Tokenization option for Main module and Express checkout.

PayPal Express - Two PayPal Tokenization Options

---

.github/workflows/e2e.yml
Api/AdyenInitPaymentsInterface.php
Model/AdyenInitPayments.php
Test/Unit/Model/AdyenInitPaymentsTest.php

PayPal Express does not support tokenization out of the box, as Google and Apple Pay do. When attempting to tokenize with PayPal, the recurringProcessingModel and storedPaymentMethod flags are not sent in with the request, causing the payment to not tokenize as it does through regular checkout.
With this PR, the Tokenization is possible for Paypal Express Payments.
Tokenizing payments for Paypal Express and Using the Tokens

PayPal Express - Tokenization not implemented

---

Model/AdyenInitPayments.php

For Paypal Express, we save an incremental orderId, but let's say if the shopper after clikcing on xyz Payment Method, abondons the order, and goes with Paypal Express, then the same id goes to the PPExpress Payment and creating a conflict and ending with Pending payment with 400 on second /paymentDetails call.
Any abondoned Payment Method with next attempt from Paypal Express.

[ECP-9661]Any PaymentMethod + PayPal Express - Double Orders

---

Observer/AbstractPaymentMethodShortcuts.php
Observer/AddApplePayShortcuts.php
Observer/AddGooglePayShortcuts.php
Observer/AddPaypalShortcuts.php
Test/Unit/Observer/AbstractPaymentMethodShortcutsTestCase.php
Test/Unit/Observer/AddApplePayShortcutsTest.php
Test/Unit/Observer/AddGooglePayShortcutsTest.php
Test/Unit/Observer/AddPaypalShortcutsTest.php
Test/Unit/Observer/UpdatePaypalOrderStatusTest.php

This PR fixes the issue of not having store scopes for configuration values for express payment methods. The PR introduces the store scope to fetch the correct configuration value based on the `store` or `website`. So that, the express payment methods will only be rendered on the stores in which the express payments are enabled.
- Use 2 stores to test express module's activation

[ECP-9610] Fix express payment store scope for configuration values

---

Helper/Util/PaypalDeliveryMethodValidator.php
Model/AdyenPaypalUpdateOrder.php
Test/Unit/Helper/Util/PaypalDeliveryMethodValidatorTest.php
Test/Unit/Model/AdyenPaypalUpdateOrderTest.php
view/frontend/web/js/actions/updatePaypalOrder.js

While setting the Shipping methods in Magento, The `detail` and `Label` of a shipping method in Magento is not a required field.
And this `detail` is mapped to the `description`(which is a required field), while send the shipping methods to PaypalExpress UpdateOrder call.
Updating the fallback mechanism to `carrierCode` if the `detail` or `Label` is not defined or empty.

[ECP-9747] Revisiting the approach to validate the Shipping Methods for PaypalUpdateOrder call

---

view/frontend/web/js/actions/updatePaypalOrder.js
view/frontend/web/js/paypal_express/button.js

When the shipping price is excluding tax, and the shipping price is 0 the flow is happy. If for example shipping is set to 5.99 the amount is rounded and the /updateOrder call fails due to the rounding up and the amount being higher than the original offer.
When changing the Flat Rate method to Price = 4.99 in the admin, the PayPal popup was displaying the **incorrect price** again because of the failing call to updateOrder, resulting in the "Unable to update address." error in the PayPal popup.
Please note that the price is output as 5.99 in the frontend, again because of the tax configuration (i.e. 4.99 + 20% VAT = ~5.99). In the call the amount is rounded up to 6.00.
This PR aims to solve the issues which handles the rounding off of the Shipping amount and also some part of the Code …

[ECP-9754] Paypal Express issues with Rounding off the shipping amount

---

.github/Dockerfile
.github/Makefile
.github/docker-compose.yml
.github/workflows/main.yml
Test/Unit/Helper/PaypalUpdateOrderTest.php
Test/Unit/Model/AdyenPaymentMethodsTest.php
Test/Unit/Model/ConfigurationTest.php
Test/Unit/Model/ExpressActivateTest.php

This PR refactors the unit tests to support PHPUnit v10. In the scope of refactoring,
- Unit test pipeline main.yml has been revisited to run PHPUnit according to Magento best practices.
- Some test cases have been added/updated.

[ECP-9773] Support PHP Unit 10 on the Express module

---

Helper/LineItemsDataBuilder.php
Model/AdyenInitPayments.php
Test/Unit/Helper/LineItemsDataBuilderTest.php
Test/Unit/Model/AdyenInitPaymentsTest.php
composer.json
etc/config.xml

This PR aims at setting `requires_line_items` configuration field to `true` for PayPal Express, then adding the `LineItems` in the `/payments` requests for Paypal Express.

[ECP-9629] Add lineItems to PayPal express /payments request
