Adyen/adyen-magento2-express-checkout

- composer.json
- etc/module.xml
Fix the tagging branch to the correct version of Composer.json
> Fix release 1.1.1 - Update Composer.json 

- .github/CODEOWNERS
- .github/release.yml
- .github/workflows/codeql.yml
- composer.json
- etc/module.xml
- view/frontend/web/js/applepay/button.js
> Release v1.1.3

- view/frontend/web/js/googlepay/button.js
- view/frontend/web/js/helpers/getRegionId.js
- view/frontend/web/js/helpers/processCountries.js
- view/frontend/web/js/model/countries.js
Correctly update tax amount on the GooglePay component when Shipping Address is changed.
- Tested with Taxed item/region
- Teste with untaxed item/region
**Fixed issue**:  
#37
> [ECP-8595] - Correctly update tax amount on the GooglePay component when Shipping Address is changed.

- .github/workflows/e2e.yml
This change adds this repository a workflow which would trigger the Express Checkout E2E tests in Adyen-Magento2 repository.
**Fixed issue**:  
ECP-8654
> [ECP-8654] Add E2E trigger workflow

- view/frontend/web/js/applepay/button.js
> Update button.js - fix $element.show()

- .github/CODEOWNERS
- .github/workflows/codeql.yml
- .github/workflows/main.yml
- composer.json
- etc/module.xml
- view/frontend/web/js/applepay/button.js
- view/frontend/web/js/googlepay/button.js
- view/frontend/web/js/helpers/getRegionId.js
- view/frontend/web/js/helpers/processCountries.js
- view/frontend/web/js/model/countries.js
> Release 2.0.0

- .github/workflows/e2e.yml
This change adds the workflow trigger for E2E tests with the active branch  of Express Checkout Module on Magento Repository
**Fixed issue**:  
ECP-8775
> [ECP-8775]Tweak express checkout e2e workflow trigger

- composer.json
- etc/module.xml
- view/frontend/web/js/googlepay/button.js
> Release 2.0.1

- Model/GetAdyenPaymentMethodsByProduct.php
- composer.json
- etc/module.xml
- view/frontend/web/js/googlepay/button.js
> Release 2.0.2

- composer.json
- etc/module.xml
- view/frontend/web/js/googlepay/button.js
> Release 1.2.1

- Api/Data/ExpressDataInterface.php
- Model/ExpressData.php
- Model/ExpressDataBuilder.php
- view/frontend/web/js/actions/getPaymentStatus.js
- view/frontend/web/js/actions/setBillingAddress.js
- view/frontend/web/js/applepay/button.js
- view/frontend/web/js/googlepay/button.js
- view/frontend/web/js/model/virtualQuote.js
This PR introduces support for virtual products on following express payment methods.
- Apple Pay
- Google Pay
- Happy flow with virtual products
- Payment flow with regular items
> [ECP-8400] Support virtual products on express payments

- ViewModel/CheckoutConfig.php
- composer.json
- view/frontend/templates/checkout-config.phtml
- view/frontend/web/js/applepay/button.js
- view/frontend/web/js/googlepay/button.js
In order to track express-checkout payment methods to gain insights into this usage, this PR adds the express method tracking fields to the payment method component configuration objects.
- Confirm internally the transactions contain the tracking values
> [ECP-9139] Provide telemetry endpoint fields to express checkout configuration objects

- README.md
Temporarily test workflow automation on live
> Test automation workflow on live

- view/frontend/web/js/paypal_express/button.js
Paypal Express for PDP doesn't works. Need to implement the same logic as we did for others in this [PR](https://github.com/Adyen/adyen-magento2-express-checkout/pull/93)
> [ECP-9336]Enable Paypal Express on PDP

- view/frontend/web/js/applepay/button.js
- view/frontend/web/js/googlepay/button.js
- view/frontend/web/js/helpers/getCurrentPage.js
- view/frontend/web/js/paypal_express/button.js
Adding `expressPage: "" ` field to express payment method component configurations.. Values can be one of "minicart", "cart", "pdp" or "checkout". 
> [ECP-9221]Provide telemetry's endpoint expressPage field to payment method component configurations

- .github/workflows/main.yml
- Model/Resolver/ExpressInitResolver.php
- Test/Unit/Model/Resolver/ExpressInitResolverTest.php
- Test/api-functional/GraphQl/AdyenExpressTest.php
- Test/bootstrap.php
- Test/phpunit.xml
- Test/phpunit_graphql.php
- composer.json
- etc/schema.graphqls
This PR introduces the GraphQL testing suite via API functional tests and adds functional tests for `expressInit` mutation.
- API functional test
> Implement GraphQL test suite

- .github/workflows/main.yml
**Description**
This PR migrates to `SonarSource/sonarqube-scan-action` action to run SonarCloud quality analysis.
**Tested scenarios**
- Main workflow
> [ECP-9625] Migrate to the new Sonarcloud action

- Model/AdyenInitPayments.php
- Test/Unit/Model/AdyenInitPaymentsTest.php
- view/frontend/web/js/applepay/button.js
- view/frontend/web/js/googlepay/button.js
- view/frontend/web/js/paypal_express/button.js
This PR aims at sending `frontendType` as ` expresscheckout` to the headers when payments are made using Express Module.
> [ECP-9631]Add FrontendType Header to the express module

- .github/workflows/e2e.yml
This PR defines missing environment variable required for Magento image build on the workflow.
> Fix Magento installation on the E2E workflow

- Model/AdyenInitPayments.php
- Model/GetAdyenPaymentMethodsByProduct.php
- Test/Unit/Model/AdyenInitPaymentsTest.php
- Test/Unit/Model/GetAdyenPaymentMethodsByProductTest.php
This PR aims to support Uplift by adding `ShopperConversionId` to the related `/payments` and `/paymentMethods` request.
> [ECP-9796] Adding ShopperConversionId for the Support of Uplift

- .github/docker-compose.yml
> [ECP-9825] Replace Bitnami Opensearch image with the official image
